// Language switcher using a translation dictionary and localStorage
document.addEventListener('DOMContentLoaded', () => {
  const translations = {
    navAbout: { ko: '단체 소개', en: 'About Us' },
    navProjects: { ko: '프로젝트', en: 'Projects' },
    navTrans: { ko: '투명성', en: 'Transparency' },
    navGallery: { ko: '갤러리', en: 'Gallery' },
    navNews: { ko: '활동 소식', en: 'News' },
    navDonate: { ko: '후원하기', en: 'Donate' },
    heroTag: { ko: '청소년 주도 비영리 단체', en: 'Youth-Led Non-Profit Organization' },
    heroTitle: { ko: '상큼한 <span style="color: #FFD93D">희망</span>을 나눕니다', en: 'Sharing Fresh <span style="color: #FFD93D">Hope</span>' },
    heroDesc: { ko: '청소년이 주도하는 투명하고 책임 있는 나눔.<br>레모네이드 포 올과 함께하세요.', en: 'Transparent and responsible giving led by youth.<br>Join us at Lemonade For All.' },
    heroDonate: { ko: '후원하기', en: 'Donate' },
    heroLearn: { ko: '더 알아보기', en: 'Learn More' },
    statProjects: { ko: '진행 중 프로젝트', en: 'Ongoing Projects' },
    statTrans: { ko: '기부금 투명 공개', en: 'Transparent Donations' },
    statCountry: { ko: '지원 대상 국가', en: 'Supported Countries' },
    statFounded: { ko: '설립 연도', en: 'Founded' },
    projectTag: { ko: '프로젝트', en: 'Projects' },
    projectTitle: { ko: '진행 중인 프로젝트', en: 'Ongoing Projects' },
    cambodiaShort: { ko: '캄보디아 취약계층 아동·청소년 가정에 의류, 보건 물품 지원', en: 'Support for clothing and health supplies for vulnerable children and youth in Cambodia' },
    campaignTitle: { ko: '기부 인식 캠페인', en: 'Donation Awareness Campaign' },
    campaignShort: { ko: '학교 및 지역사회 공익 활동 교육 및 기부 캠페인', en: 'Public service education and donation campaign for schools and communities' },
    viewDetail: { ko: '상세 보기 →', en: 'View Details →' },
    allProjects: { ko: '모든 프로젝트 보기', en: 'View All Projects' },
    ctaTitle: { ko: '지금 함께해주세요', en: 'Join Us Now' },
    ctaDesc: { ko: '여러분의 작은 나눔이 세상을 바꿉니다', en: 'Your small contribution changes lives' },
    ctaDonate: { ko: '후원하기', en: 'Donate' },
    footerDesc: { ko: '청소년이 만드는 투명한 나눔', en: 'Transparent giving led by youth' },
    statusActive: { ko: '활동 중', en: 'Active' },
    gallery_doc: { ko: 'Lemonade For All | 갤러리', en: 'Lemonade For All | Gallery' },
    galleryTag: { ko: '우리들의 순간', en: 'Our Moments' },
    galleryTitle: { ko: '갤러리', en: 'Gallery' },
    galleryDesc: { ko: '레모네이드 포 올 팀원들이 직접 담은 활동 현장의 순간들입니다.', en: 'Moments captured directly by our Lemonade For All team members.' },
    filterAll: { ko: '전체', en: 'All' },
    filterCambodia: { ko: '캄보디아', en: 'Cambodia' },
    filterCampaign: { ko: '캠페인', en: 'Campaign' },
    filterTeam: { ko: '팀 활동', en: 'Team' },
    // Project detail keys
    cambodia_page_title: { ko: 'Lemonade For Cambodia', en: 'Lemonade For Cambodia' },
    cambodia_page_sub: { ko: '캄보디아 취약계층 아동·청소년에게 따뜻한 나눔을 전합니다', en: 'Bringing warm support to vulnerable children and youth in Cambodia' },
    cambodia_overview: { ko: '프로젝트 개요', en: 'Project Overview' },
    cambodia_desc: { ko: 'Lemonade For Cambodia 프로젝트는 캄보디아 취약계층 아동·청소년 가정을 대상으로 의류, 보건 물품 등 생활 필수품을 지원하는 프로젝트입니다.', en: 'The Lemonade For Cambodia project provides essential items such as clothing and health supplies to vulnerable children and youth households in Cambodia.' },
    cambodia_support: { ko: '지원 내용', en: 'Support Details' },
    support_item_1: { ko: '의류 및 신발 제공', en: 'Provision of clothing and shoes' },
    support_item_2: { ko: '보건 위생 물품 지원', en: 'Health and hygiene supplies' },
    support_item_3: { ko: '학용품 및 교육 자료 전달', en: 'School supplies and educational materials' },
    support_item_4: { ko: '기본 생활 필수품 제공', en: 'Basic living essentials' },
    cambodia_partner: { ko: '파트너', en: 'Partners' },
    cambodia_impact: { ko: '기대 효과', en: 'Expected Impact' },
    cambodia_partner_desc: { ko: '태화복지재단 캄보디아 지부와의 공식 협력을 통해 모든 기부 물품이 캄보디아 현지에 안전하고 투명하게 전달됩니다. 전문 NGO와의 협력으로 신뢰할 수 있는 지원 체계를 구축했습니다.', en: 'Through official cooperation with the Cambodia branch of Taehwa Welfare Foundation, all donated items are delivered safely and transparently to Cambodia. Collaboration with professional NGOs ensures a reliable support system.' },
    cambodia_impact_desc: { ko: '취약계층 아동들의 기본적인 생활 환경을 개선하고, 건강하고 안전한 성장을 지원합니다. 장기적으로 교육 기회 확대와 자립 기반 마련에 기여하고자 합니다.', en: 'Improve basic living conditions for vulnerable children, support healthy and safe growth, and contribute to expanded educational opportunities and self-reliance in the long term.' },
    donate_project_btn: { ko: '이 프로젝트 후원하기', en: 'Support this project' },
    // Campaign page keys
    campaign_page_title: { ko: '기부 인식 캠페인', en: 'Donation Awareness Campaign' },
    campaign_page_sub: { ko: '청소년이 직접 만들어가는 투명한 기부 문화', en: 'Youth-led transparent donation culture' },
    campaign_overview: { ko: '프로젝트 개요', en: 'Project Overview' },
    campaign_desc: { ko: '기부 인식 캠페인은 학교 및 지역사회에서 공익 활동 교육과 기부 참여를 촉진하는 프로젝트입니다.', en: 'The Donation Awareness Campaign promotes public service education and donation participation in schools and communities.' },
    campaign_activities: { ko: '주요 활동', en: 'Main Activities' },
    campaign_item_1: { ko: '학교 기부 교육 프로그램 진행', en: 'School donation education programs' },
    campaign_item_2: { ko: '지역사회 봉사 활동 조직', en: 'Organize community volunteer activities' },
    campaign_item_3: { ko: '국제사회 현안 저널 및 콘텐츠 제작', en: 'Produce journals and content on international issues' },
    campaign_item_4: { ko: '청소년 나눔 문화 확산 캠페인', en: 'Campaign to spread youth sharing culture' },
    campaign_impact: { ko: '기대 효과', en: 'Expected Impact' },
    campaign_impact_desc: { ko: '청소년들이 기부와 나눔의 가치를 이해하고 실천하는 계기를 마련합니다. 투명한 기부 문화를 확산하여 사회 전반의 나눔 의식을 높이는 것을 목표로 합니다.', en: 'It provides opportunities for youth to understand and practice the value of giving, aiming to spread a transparent donation culture and raise awareness across society.' },
    campaign_join_btn: { ko: '함께 참여하기', en: 'Join Us' },

    // News page keys
    news_doc: { ko: '활동 소식 | Lemonade For All', en: 'News | Lemonade For All' },
    news_title: { ko: '활동 소식', en: 'News' },
    news_sub: { ko: '레모네이드 포 올의 최근 소식과 활동 내용을 확인하세요', en: 'Check out the latest news and activities from Lemonade For All' },
    news1_title: { ko: '캄보디아 1차 물품 지원 완료', en: 'First Aid Delivery to Cambodia Completed' },
    news1_desc: { ko: "캄보디아 반띠민쩨이(Banteay Meanchey) 도시의 주정부 운영 고아원 'Place of Rescue'에 물품을 전달했습니다. 이곳에는 캄보디아-태국 국경분쟁으로 고아가 된 12명의 아이들을 포함해 총 113명의 고아들이 지내고 있습니다. 태화복지재단 캄보디아 지부와 협력하여 현지 아이들에게 의류 및 보건 물품을 성공적으로 전달했습니다.", en: "We delivered supplies to 'Place of Rescue,' a government-run orphanage in Banteay Meanchey, Cambodia. The orphanage houses 113 children, including 12 orphaned by the Cambodia-Thailand border conflict. In cooperation with the Cambodia branch of Taehwa Welfare Foundation, we successfully delivered clothing and health supplies to the children there." },
    news2_title: { ko: '학교 기부 캠페인 진행', en: 'School Donation Campaign Held' },
    news2_desc: { ko: '포항 지역 학교에서 공익 활동 교육 캠페인을 진행하며 청소년 나눔 문화 확산에 기여했습니다. 200여 명의 학생들이 참여했습니다.', en: 'We held a public service education campaign at schools in Pohang, contributing to the spread of a youth sharing culture. About 200 students participated.' },
    news3_title: { ko: '레모네이드 포 올 공식 창립', en: 'Lemonade For All Officially Founded' },
    news3_desc: { ko: '청소년 주도의 비영리 단체 레모네이드 포 올이 공식 창립되었습니다. 함께해주셔서 감사합니다.', en: 'Lemonade For All, a youth-led non-profit organization, has been officially founded. Thank you for joining us.' },
